import React from 'react'

const Comp2 = () => {
  return (
      <div style={{textAlign:"center"}}>
          <h1>Learn Web Developmemt</h1>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Magnam pariatur fugiat quidem numquam error distinctio neque nulla quia rerum velit iure expedita, vitae animi repellendus amet dolorum voluptas voluptates accusantium magni aliquid nostrum delectus, natus quae atque. Magni quisquam harum quas rem maiores facilis, rerum cumque officia explicabo necessitatibus. Dolor amet provident, dolores, unde iusto laudantium quidem quas assumenda, quis officiis veniam recusandae asperiores quisquam labore exercitationem excepturi alias in laborum omnis at ea delectus velit! Exercitationem aliquam impedit alias! Modi, laborum! Dolor facilis doloribus possimus? Expedita debitis illo sunt doloremque quisquam nihil, assumenda ratione earum similique eaque voluptatum
              <a href="/">the rest of MDN</a>
              ipsa id quam odit! Mollitia accusamus iure eveniet ipsam corporis aliquid, eum nulla libero minus distinctio ipsa molestiae vero facere dolorum porro tenetur magni ex! Blanditiis quo amet quos! Tempora obcaecati suscipit sint. Culpa nam temporibus voluptate id veniam, fugiat quidem! Dignissimos nobis quae odio labore optio officia eos facere, delectus aspernatur perferendis praesentium soluta, possimus ullam voluptatibus tenetur et necessitatibus natus debitis hic! Tenetur unde minima enim iure, labore neque. Debitis exercitationem recusandae enim non. Enim possimus, asperiores pariatur recusandae error molestias maxime repellendus animi, ut obcaecati molestiae quos vero necessitatibus sequi blanditiis doloremque accusamus expedita, facilis perspiciatis rem eos reiciendis? Assumenda repudiandae alias doloremque inventore non odit neque quis blanditiis totam, ullam numquam vitae ex, omnis ad aspernatur earum id ut quibusdam rerum tempore, eos natus! Necessitatibus voluptatibus enim atque, suscipit sunt, explicabo id assumenda totam voluptate harum quasi rerum incidunt fugiat. Quae facere saepe iusto, distinctio unde dolorem, neque necessitatibus eos fuga vero voluptas repellendus! Ipsum provident officia ipsa voluptate, nesciunt, ad quibusdam doloribus minima eius similique sequi blanditiis modi aut eaque porro, cupiditate quam est consequatur! Dolorum porro voluptates illo dicta velit magni ullam quo sed, iste aliquid, amet vel deleniti, mollitia cum numquam. Molestias architecto fugiat iusto impedit esse atque officia veniam quae beatae labore itaque, assumenda provident nulla, reprehenderit et odio sint sit quod voluptatem in amet eius culpa autem. Suscipit cum officia reprehenderit vel. Praesentium voluptas ipsam asperiores veniam laboriosam itaque vitae odio, dolore fugiat quo modi debitis deleniti? Corrupti deleniti laudantium ad fugiat vel at delectus suscipit exercitationem impedit, maiores animi debitis velit amet maxime sit adipisci possimus, minus provident iusto quae alias. Nemo odit consectetur quo eius necessitatibus dignissimos quia, voluptatum reprehenderit. Temporibus nihil officiis esse, numquam id beatae odit quam. Ipsam quisquam quae maxime harum officiis voluptatum voluptate suscipit minima dignissimos!</p>
    </div>
  )
}

export default Comp2